.TH iespo 1 "February 16, 1994"
.SH NAME iespo
.SH
\fBiespo\fP \- enumeration of equations  and  inequalities  that
        are valid for a convex cone and a convex hull
.SH SYNOPSIS
.nf
        iespo [-v] fname_with_'.ieq' fname_with_'.poi'
.SH DESCRIPTION
iespo is a simple enumeration routine which enumerates the subset
of equations  and  inequalities in the 'ieq' input file which are valid 
(not necessarily facet inducing) for the polyhedron given by the 
'poi' input  file.   
.sp1
The output is written into an 'ieq'-file, whose name is derived
from the 'poi'-input filename.
.SH OPTIONS
.nf
    -v Prints a table  in  the  output  file  which  indicates
       strong validity
.so man1/poiieq.1
.SH SEE ALSO
porta(1), dim(1), fmel(1), portsort(1), traf(1),
fctp(1), posie(1), vint(1)
rt(1), traf(1),
fctp(1), posie(1), vint(1)
