.TH posie 1 "February 17, 1994"
.SH NAME posie
.SH
\fBposie\fP \- enumeration of points that are valid for a linear
        system
.SH SYNOPSIS
.nf
        posie fname_with_suffix_'.ieq' fname_with_suffix_'.poi'
.SH DESCRIPTION
posie is a simple enumeration routine which determines the number 
of the points and direction vectors in the '.poi'-file
which are valid for the linear system in the '.ieq'-file. 
.sp1
The output is written into a  'poi'-file, whose name is derived
from the 'ieq'-input filename.
.so man1/poiieq.1
.SH SEE ALSO
porta(1), dim(1), fmel(1), iespo(1), portsort(1), traf(1),
fctp(1), vint(1)
af(1),
fctp(1), vint(1)
